"""Add missing columns

Revision ID: 04cedc83bcb1
Revises: 9785bf261328
Create Date: 2026-02-10 10:12:18.389464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04cedc83bcb1'
down_revision: Union[str, None] = '9785bf261328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['project_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_project', 'jobs', ['project_id'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_type', 'jobs', ['job_type'], unique=False)
    op.add_column('integration_configs', sa.Column('api_base_url', sa.String(length=500), nullable=True))
    op.add_column('integration_configs', sa.Column('auth_type', sa.String(length=20), nullable=True))
    op.add_column('integration_configs', sa.Column('auth_credentials', sa.String(length=1000), nullable=True))
    op.add_column('integration_configs', sa.Column('status_endpoint', sa.String(length=255), nullable=True))
    op.add_column('integration_configs', sa.Column('status_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('integration_configs', sa.Column('update_method', sa.String(length=20), nullable=True))
    op.add_column('integration_configs', sa.Column('polling_interval_seconds', sa.Integer(), nullable=True))
    op.add_column('integration_configs', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.add_column('integration_configs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('project_versions', sa.Column('release_id', sa.String(length=50), nullable=True))
    op.add_column('project_versions', sa.Column('release_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('current_release_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'current_release_id')
    op.drop_column('project_versions', 'release_url')
    op.drop_column('project_versions', 'release_id')
    op.drop_column('integration_configs', 'retry_count')
    op.drop_column('integration_configs', 'timeout_seconds')
    op.drop_column('integration_configs', 'polling_interval_seconds')
    op.drop_column('integration_configs', 'update_method')
    op.drop_column('integration_configs', 'status_mapping')
    op.drop_column('integration_configs', 'status_endpoint')
    op.drop_column('integration_configs', 'auth_credentials')
    op.drop_column('integration_configs', 'auth_type')
    op.drop_column('integration_configs', 'api_base_url')
    op.drop_index('ix_jobs_type', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_project', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
