"""add_level_to_assets

Revision ID: acda00a0a4a6
Revises: 04cedc83bcb1
Create Date: 2026-02-11 03:14:42.536068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acda00a0a4a6'
down_revision: Union[str, None] = '04cedc83bcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('level', sa.String(length=100), nullable=True))
    op.create_index('ix_assets_version_level', 'assets', ['version_id', 'level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_version_level', table_name='assets')
    op.drop_column('assets', 'level')
    # ### end Alembic commands ###
